### ISSUE TITLE
Body must be bytes and should not contain wide characters

### ISSUE THREAD

**Issue by KES777** [plack/Plack#522]
If I have set correct 'charset' header, use utf8, but Lint is complaining me still. 
Do you forget to check 'Content-Type' charset before throw this error?

This is test.html mason file:
```
<body><pre>
% use utf8;
% $r->query->charset( 'utf-8' );
%# print "\x{2780}"; #has no matter which variant to use
% print "➀";
</pre></body>
```

```
$curl -i http://site/test.html
TTP/1.1 200 OK
Server: nginx/1.6.2
Date: Sat, 05 Sep 2015 15:28:53 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: plack_session=9e799278056db3632b019e90f54de22e6ea3f25f; path=/



<body><pre>
➀</pre></body>

```

The browser do correct displaying.

**Comment by miyagawa** [comment]
your app is violating the specification of PSGI where the body has to be raw bytes and should not contain wide characters: http://search.cpan.org/~miyagawa/PSGI-1.102/PSGI.pod#SPECIFICATION

Some web servers will still render them correctly because perl internals store them in utf8 **by accident**, and that's not the feature we support.
