### ISSUE TITLE
[uwsgi-perl error] Not an ARRAY reference at Plack/Middleware/Lint.pm line 155

### ISSUE THREAD

**Issue by KES777** [plack/Plack#533]
[DOC](http://search.cpan.org/~miyagawa/PSGI-1.102/PSGI.pod#Body): 
    The response body MUST be returned from the application as either an array reference or a **handle**

The Lint expects only an array
```
155:    if (ref $res->[2] eq 'ARRAY' && grep _has_wide_char($_), @{$res->[2]}) {
```

The example code:
```
$app =  builder {
# builder {
    enable 'Session', store => 'File';
    enable 'Lint';
    mount '/test' => builder {
        my $server = Mojo::Server::PSGI->new;
        $server->build_app( 'MyApp' );
        sub{ $server->run( @_ ) };
    };
    mount '/' => builder { $mason_app };
};
```

Here $server->run returns:
```
  # PSGI response
  my $io = Mojo::Server::PSGI::_IO->new(tx => $tx, empty => $tx->is_empty);
  return [$res->code // 404, \@headers, $io];
```

**Comment by miyagawa** [comment]
> The Lint expects only an array

No, that code only checks that *if* the response body is an array, it *should not* contain wide characters in the body. It is ok to pass a handle. That array dereferencing only happens when `$res->[0]` is actually an ARRAY ref, so that error makes no sense.

Does your code run with plackup, not uwsgi? It seems like a bug with uwsgi. I recommend turning off Lint with uwsgi, or report the issue back to uwsgi.

**Comment by KES777** [comment]
Yes, you are right. Under `plack script.pl` works fine. But now we can notice that Lint does not check wide charecters when [2] is iohandle.
