### ISSUE TITLE
Request url parameters not utf8 decoded

### ISSUE THREAD

**Issue by nicolasfranck** [plack/Plack#626]
When processing the request parameters, I discovered that the values
are not utf8-decoded:

```
#!/usr/bin/env perl
use strict;
use utf8;
use feature qw(:5.10);
use Plack::Builder;
use Plack::Request;

builder {

    mount "/" => sub {

        my $env = $_[0];

        my $request = Plack::Request->new( $env );
        my $params  = $request->query_parameters();

        my @body;
        for my $key ( $params->keys() ) {

            my(@values) = $params->get_all( $key );

            for my $val ( @values ) {

                push @body, "$key = $val", " (utf8:", utf8::is_utf8($val) ? "true":"false",")";

            }

        }

        [ 200, [ "Content-Type" => "text/plain; charset=utf-8" ], \@body ];

    };

};
```

Is this intended? I thought url parameters were supposed to contain utf8 characters.

**Comment by miyagawa** [comment]
Yes this is intended, since in HTTP we do not know the encoding of the request body and query parameters. it could be utf-8, or shift_jis, or latin-1, depending on what encoding the form was served.

The majority of the request nowadays should be served in UTF-8, but as a framework Plack cannot and should not make that decision. There should be a layer between Plack and your application, namely a framework you're using, to make that decision for you.
