### ISSUE TITLE
Minimum version is inconsistent

### ISSUE THREAD

**Issue by robrwo** [plack/Plack#701]
The minimum version in cpanfile is set to v5.12 but a lot of the code, and the minimum version according to metacpan, is still 5.8.

**Comment by miyagawa** [comment]
This is because most of Plack actually runs on 5.8 just fine, but because the downstream dependencies require 5.12 (even 5.14 actually) I needed to update the distribution's dependency to make sure I don't get false reports.

I see no reason to update each file to 5.12 etc. because these code work just fine on older perls if they manually grab and install the distribution and there's no need to torture them further.
